### ISSUE TITLE
Possible to combine with symbol override?

### ISSUE THREAD

**Issue by MDBas** [kenmoore/sketch-relabel-button#13]
Hi, 

Any idea if it's possible to use this plugin in combination with a symbol override and/or smart symbol resizing from sketch 39 release?

We're using buttons for which the width of the container has a fixed left and right padding (text centered).
The button can also contain an icon width 

What I would like to do:
- Create a button symbol
- When I use this button symbol somewhere, adjust the label of the button with the override feature
- Have the width of the button update, respecting the left and right padding.

Since this plugin can only be used for groups and not symbols, I can not adjust only the instance of a symbol.

Sketch 39 release is awesome, but doesn't fix this as far as I know.

**Comment by ohheyyeahthatsme** [comment]
I'd love to have the same thing—the ability to set my buttons as symbols and then cmd+J to change the text & auto resize background.

**Comment by alexeiboronnikov** [comment]
I've got absolutely the same request here. Cmd+J would be super useful for symbols.

**Comment by akoskinen** [comment]
+1 I hope bohemian coding will add this to the symbols functionality in v.40.

**Comment by fuggfuggfugg** [comment]
@kenmoore 
I currently maintain the Sketch Dynamic Button. I have been [getting these requests](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/issues/19) for Symbol Support too. [I finally gave it a shot at I may have something working.](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/tree/sketch-symbols-fuck-yeah) 

You are [most welcome to reuse the code](https://github.com/fuggfuggfugg/sketch-dynamic-button-3.5/blob/sketch-symbols-fuck-yeah/DynamicButton3.5.sketchplugin/Contents/Sketch/script.cocoascript#L118-L155) for your plugin.

**Comment by kenmoore** [comment]
@fuggfuggfugg Thanks for the nudge and for the symbols code!  I've updated the plugin to (finally) use the proper bundle format, and to support symbols.  Much appreciated.

@akoskinen @alexeiboronnikov @ohheyyeahthatsme @MDBas ... please check out the new support for symbols and let me know if anything misbehaves!

**Comment by kenmoore** [comment]
@abailon @rubiroid @alexeiboronnikov @tomdeforest @benske ... check out symbols support, let me know if you encounter any issues.

**Comment by donbailon** [comment]
@kenmoore Hi, I tried but doesn't works fine. It's a bit weird to use. When you create a symbol, you need to override the text with another text for works properly because when you import a symbol the text value is empty by default. 

For example if I create a button with the text "action" and later I convert it to symbol, when I import the button symbol I need to put "Action" in the textfield input for write the same text that the original symbol and not change the paddings and later we can use the plugin but, it's very weird.

<img width="212" alt="screen shot 2017-03-06 at 16 00 22" src="https://cloud.githubusercontent.com/assets/8384392/23617815/3529982e-0286-11e7-986b-a6ef909c1e8f.png">

BTW: keep it up with the great work, this plugin is a must have!

**Comment by kenmoore** [comment]
@abailon @MDBas  thanks for the info, I realized what I was doing wrong and have posted a fix.  I've bumped the version to 1.1.  I'm pretty confident it will work now, your feedback here has been super helpful.

**Comment by donbailon** [comment]
@kenmoore We have another problem. It add an extra padding.

The first button is a symbol without text in the input, and the last one is the symbol overridden with your plugin.

<img width="341" alt="screen shot 2017-03-06 at 17 00 38" src="https://cloud.githubusercontent.com/assets/8384392/23620364/8b93bb88-028e-11e7-90c3-6cd0ed637e38.png">

**Comment by kenmoore** [comment]
@abailon Sorry there, I'm being a bit too hasty here.  I've found and fixed the issue, please have another try.

**Comment by donbailon** [comment]
yeah! @kenmoore works fine! thanks a lot for your work

**Comment by tomdeforest** [comment]
Tested and working as advertised. Super sweet!!!

**Comment by kenmoore** [comment]
@tomdeforest Awesome, thanks for letting me know.

**Comment by MDBas** [comment]
Yes, it's working! Thanks a lot.

**Comment by benoitboucart** [comment]
Awesome!

**Comment by bobmatteo** [comment]
@kenmoore Awesome job! This would be even better if this works with nested symbols. I currently try to use one symbol for most of my inputs for example where the long label is a symbol as well:

![input-example](https://cloud.githubusercontent.com/assets/8168202/23667423/142904ce-035e-11e7-9bdf-fdc7757908be.png)

**Comment by kenmoore** [comment]
@bobmatteo could you attach a Sketch file with a sample nested symbol object you'd expect it to work with?  I can't promise I'll get to this soon, but will have a look and update the plugin if it's not too challenging.

**Comment by fuggfuggfugg** [comment]
I've received the same requests, I did spend some time on this 2 days ago. I can provide some insight.  

It's a bit challenging since each user has their own way of using creating buttons symbols and overrides. Some users have created symbols for each layer within the Dynamic button in my case so they can have one symbol and multiple overrides for text, bg color, etc. Some also apply the padding in a different layer. This changes the fact that I have to now uniquely identify the layer inside nested symbols which has the padding and then work backwards. 

Also there's not much documentation so it gets very frustrating at times. For now, 

* I finally found a way to add tags to uniquely identify my layers. 
* I also have recursive logic to traverse through all the children. 

Currently stuck at figuring out how to traverse through all overrides and get the value of the text so I can calculate the width and add padding. 

Dynamic Button was meant for simple stuff before symbols overrides came along. Quite challenging however if I can crack this, It'd be pretty awesome.

**Comment by bobmatteo** [comment]
@kenmoore I've attached a sketch file with a base setup for buttons and inputs. Both symbols exists of multiple nested symbols. This way I would be able to create lots of different types of UI elements with only the use of overrides. Unfortunately I can't change the width of the nested symbols via overrides.

[nested-symbols.sketch.zip](https://github.com/kenmoore/sketch-relabel-button/files/827271/nested-symbols.sketch.zip)

@fuggfuggfugg I can understand this can be quite challenging. Currently I'm working with different background layers which I apply the padding to. But I'm also using the resizing feature in Sketch, which I recommend always to check, like "Pin to corner" and "Resize object". Therefore if the width of the symbol(artboard) changes based on the text element inside, all my children layers will adjust accordingly. Fyi I also use the [Auto Layout plugin](https://animaapp.github.io/Auto-Layout/) to fine tune the resizing of elements. This approach will be a bit easier I guess but that would not solve all scenarios.

When the symbols and overrides came along I become very hyped about it. I still am but the more I'm using it the more ideas I get for improvements as well. Let me know if you want to talk about those ideas ;)

As I can read you have put quite some work in it, huge thanks to both of you and the rest! Keep up the amazing work! If this is going to happen, hell yeah would be awesome for sure!!! This almost makes me forget about [Subform](https://www.subformapp.com)...
